### ISSUE TITLE
ToastUtils存在bug

### ISSUE THREAD

**Issue by Aallizzwell** [AlanCheen/Pandora#2]
Toast调用cancel后立马调用show是没有效果的。在执行handleShow的时候会进行if (mHandler.hasMessages(CANCEL) || mHandler.hasMessages(HIDE))判断，因为mHandler的messageQueue存在HIDE，所以show方法不会执行。

**Comment by czn6** [comment]
我试试看哈 谢谢反馈

**Comment by czn6** [comment]
已经 Fix 谢谢反馈
